2020-03-20 12:18:48,410 [WARNING]- Not Found: /yo
2020-03-20 12:25:16,241 [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/rik/nosedive/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rik/nosedive/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rik/nosedive/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/nosedive/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rik/nosedive/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/rik/nosedive/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/home/rik/nosedive/main/views.py", line 25, in get_context_data
    logger.info(self.request.user + " opened /")
TypeError: unsupported operand type(s) for +: 'SimpleLazyObject' and 'str'
